/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 gBuildingDraco.glb --types 
Author: naam (https://sketchfab.com/naam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-big-g-building-ba2b84dbcded4f309ad14f39e2c83932
Title: The Big G Building
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
  };
  materials: {
    mat6: THREE.MeshStandardMaterial;
    mat10: THREE.MeshStandardMaterial;
    mat11: THREE.MeshStandardMaterial;
    mat12: THREE.MeshStandardMaterial;
    mat13: THREE.MeshStandardMaterial;
    mat14: THREE.MeshStandardMaterial;
    mat15: THREE.MeshStandardMaterial;
    mat16: THREE.MeshStandardMaterial;
    mat17: THREE.MeshStandardMaterial;
    mat18: THREE.MeshStandardMaterial;
    mat19: THREE.MeshStandardMaterial;
    mat2: THREE.MeshStandardMaterial;
    mat20: THREE.MeshStandardMaterial;
    mat21: THREE.MeshStandardMaterial;
    mat22: THREE.MeshStandardMaterial;
    mat23: THREE.MeshStandardMaterial;
    mat24: THREE.MeshStandardMaterial;
    mat3: THREE.MeshStandardMaterial;
    mat4: THREE.MeshStandardMaterial;
    mat5: THREE.MeshStandardMaterial;
    mat7: THREE.MeshStandardMaterial;
    mat8: THREE.MeshStandardMaterial;
    mat9: THREE.MeshStandardMaterial;
  };
  //   animations: GLTFAction[];
};

export function GBuilding(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/gBuildingDraco.glb") as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group
        position={[0.5, -0.5, 0]}
        rotation={[-Math.PI / 1.6, 0, 2]}
        scale={1.719}
      >
        <mesh geometry={nodes.Object_2.geometry} material={materials.mat6} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.mat10} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.mat11} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.mat12} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.mat13} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.mat14} />
        {/* <mesh geometry={nodes.Object_8.geometry} material={materials.mat15} /> */}
        {/* <mesh geometry={nodes.Object_9.geometry} material={materials.mat16} /> */}
        {/* <mesh geometry={nodes.Object_10.geometry} material={materials.mat17} /> */}
        <mesh geometry={nodes.Object_11.geometry} material={materials.mat18} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.mat19} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.mat2} />
        {/**
         * Ground
         */}
        {/* <mesh geometry={nodes.Object_14.geometry} material={materials.mat20} /> */}
        <mesh geometry={nodes.Object_15.geometry} material={materials.mat21} />
        {/* <mesh geometry={nodes.Object_16.geometry} material={materials.mat22} /> */}
        {/* <mesh geometry={nodes.Object_17.geometry} material={materials.mat23} /> */}
        <mesh geometry={nodes.Object_18.geometry} material={materials.mat24} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.mat3} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.mat4} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.mat5} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.mat7} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.mat8} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.mat9} />
      </group>
    </group>
  );
}

useGLTF.preload("/gBuildingDraco.glb");
